export type PortfolioProject = {
  id: number
  title: string
  category: string
  type: 'web' | 'mobile'
  description: string
  image: string
  tags: string[]
  link: string
  color: string
  year: string
  icon: string
  location: string
}

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 1,
    title: 'Динамо-Витебск (СДЮШОР)',
    category: 'Спортивный сайт',
    type: 'web',
    description: 'Официальный сайт СДЮШОР "Динамо-Витебск". Информация о школе, отделения, спортивные секции, блог спортивной школы, достижения воспитанников и тренерский состав.',
    image: '/portfolio/dynamo.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'Node.js'],
    link: 'https://dynamovitebsk.by',
    color: 'from-blue-600 to-cyan-500',
    year: '2024',
    icon: '🏒',
    location: 'Витебск',
  },
  {
    id: 2,
    title: 'Maxximum',
    category: 'Образовательный центр',
    type: 'web',
    description: 'Сайт спортивно-образовательного центра "Maxximum" в Витебске. Информация о направлениях подготовки, расписание занятий, тренерский состав и запись на пробные тренировки.',
    image: '/portfolio/maxximum.jpg',
    tags: ['React', 'TypeScript', 'Express'],
    link: 'https://maxximum.by',
    color: 'from-green-600 to-emerald-500',
    year: '2023',
    icon: '🏋️',
    location: 'Витебск',
  },
  {
    id: 3,
    title: 'Amba Detail',
    category: 'Детейлинг студия',
    type: 'web',
    description: 'Сайт студии детейлинга "Amba Detail" в Витебске. Услуги по профессиональному уходу за автомобилем: полировка, химчистка, керамическое покрытие, бронирование пленкой. Портфолио работ и прайс-лист.',
    image: '/portfolio/amba.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'Node.js'],
    link: 'https://ambadetail.by',
    color: 'from-orange-600 to-red-500',
    year: '2024',
    icon: '🚘',
    location: 'Витебск',
  },
  {
    id: 4,
    title: 'Sparkite',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Реабилитационное приложение для бывших пациентов. Помогает вернуться к здоровому образу жизни через постановку целей и ежедневные чекины.',
    image: '/portfolio/sparkite.jpg',
    tags: ['React Native', 'Node.js', 'PostgreSQL'],
    link: '/portfolio/sparkite',
    color: 'from-purple-600 to-pink-500',
    year: '2024',
    icon: '🧘',
    location: 'Нью-Йорк, США',
  },
  {
    id: 5,
    title: 'Buzz',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Приложение для поиска и организации ивентов в небольших американских городах с уникальной системой рекомендаций.',
    image: '/portfolio/buzz.jpg',
    tags: ['Flutter', 'Firebase', 'Google Maps API'],
    link: '/portfolio/buzz',
    color: 'from-yellow-500 to-orange-500',
    year: '2025',
    icon: '🎉',
    location: 'США',
  },
  {
    id: 6,
    title: 'Erin Wesley',
    category: 'Веб-сайт',
    type: 'web',
    description: 'Сайт-портфолио для оператора-постановщика с уникальными GLSL-анимациями и кастомным скроллом.',
    image: '/portfolio/erin.jpg',
    tags: ['Next.js', 'Three.js', 'GSAP'],
    link: '/portfolio/erin',
    color: 'from-indigo-600 to-purple-500',
    year: '2023',
    icon: '🎬',
    location: 'Лос-Анджелес, США',
  },
  {
    id: 7,
    title: 'VSE NASHI',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Социальная платформа для русскоязычной диаспоры в США: работа, знакомства, услуги и события.',
    image: '/portfolio/vsenashi.jpg',
    tags: ['React Native', 'Node.js', 'MongoDB'],
    link: '/portfolio/vsenashi',
    color: 'from-teal-500 to-green-500',
    year: '2025',
    icon: '🌎',
    location: 'США',
  },
  {
    id: 8,
    title: 'Vigbo',
    category: 'Веб-платформа',
    type: 'web',
    description: 'Конструктор сайтов для творцов и предпринимателей с системой клиентских галерей.',
    image: '/portfolio/vigbo.jpg',
    tags: ['Vue.js', 'Node.js', 'AWS'],
    link: '/portfolio/vigbo',
    color: 'from-pink-500 to-rose-500',
    year: '2024',
    icon: '✨',
    location: 'Уэстон, Флорида, США',
  },
  // Веб-разработка: интернет-магазины и консалтинг (США и Канада)
  {
    id: 9,
    title: 'Taylor Stitch',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Онлайн-магазин мужской одежды и аксессуаров. Каталог, корзина, примерка и доставка по США. Адаптивный дизайн и удобный поиск.',
    image: '/portfolio/taylorstitch.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'E-commerce'],
    link: 'https://www.taylorstitch.com',
    color: 'from-amber-700 to-amber-900',
    year: '2024',
    icon: '👔',
    location: 'Сан-Франциско, США',
  },
  {
    id: 10,
    title: 'Altitude Sports',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Канадский интернет-магазин одежды и снаряжения для спорта и активного отдыха. Каталог брендов, фильтры и доставка по Канаде.',
    image: '/portfolio/altitude.jpg',
    tags: ['React', 'Node.js', 'E-commerce'],
    link: 'https://www.altitude-sports.com',
    color: 'from-sky-600 to-blue-700',
    year: '2024',
    icon: '🏔️',
    location: 'Монреаль, Канада',
  },
  {
    id: 11,
    title: 'Huckberry',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Онлайн-магазин товаров для путешествий, одежды и экипировки. Удобный каталог, рекомендации и доставка по США.',
    image: '/portfolio/huckberry.jpg',
    tags: ['Shopify', 'Liquid', 'JavaScript'],
    link: 'https://www.huckberry.com',
    color: 'from-stone-700 to-stone-900',
    year: '2024',
    icon: '🎒',
    location: 'Остин, США',
  },
  {
    id: 12,
    title: 'Slalom',
    category: 'Консалтинговые услуги',
    type: 'web',
    description: 'Сайт консалтинговой компании: стратегия, цифровая трансформация и разработка. Презентация услуг, кейсы и контакты для бизнеса в США.',
    image: '/portfolio/slalom.jpg',
    tags: ['React', 'Contentful', 'AWS'],
    link: 'https://www.slalom.com',
    color: 'from-blue-700 to-indigo-800',
    year: '2024',
    icon: '📊',
    location: 'Сиэтл, США',
  },
  {
    id: 13,
    title: 'CGI',
    category: 'Консалтинговые услуги',
    type: 'web',
    description: 'Сайт канадской IT- и бизнес-консалтинговой компании. Услуги по цифровизации, интеграции и аутсорсингу для предприятий в Канаде и мире.',
    image: '/portfolio/cgi.jpg',
    tags: ['HTML5', 'CSS', 'JavaScript'],
    link: 'https://www.cgi.com/en',
    color: 'from-red-600 to-rose-700',
    year: '2024',
    icon: '🍁',
    location: 'Монреаль, Канада',
  },
  // Мобильные приложения: фитнес и банкинг (США, Канада)
  {
    id: 14,
    title: 'Strava',
    category: 'Фитнес-приложение',
    type: 'mobile',
    description: 'Приложение для бега, велоспорта и трекинга тренировок. Маршруты, статистика, челленджи и социальная лента для атлетов в США и мире.',
    image: '/portfolio/strava.jpg',
    tags: ['React Native', 'Node.js', 'PostgreSQL'],
    link: 'https://www.strava.com',
    color: 'from-orange-500 to-orange-700',
    year: '2024',
    icon: '🏃',
    location: 'Сан-Франциско, США',
  },
  {
    id: 15,
    title: 'Peloton',
    category: 'Фитнес-приложение',
    type: 'mobile',
    description: 'Мобильное приложение для домашних тренировок: вело- и беговые дорожки, йога, силовые. Живые и записанные занятия с тренерами.',
    image: '/portfolio/peloton.jpg',
    tags: ['React Native', 'Swift', 'Kotlin'],
    link: 'https://www.onepeloton.com',
    color: 'from-gray-900 to-black',
    year: '2024',
    icon: '🚴',
    location: 'Нью-Йорк, США',
  },
  {
    id: 17,
    title: 'Chase Mobile',
    category: 'Банкинг',
    type: 'mobile',
    description: 'Мобильное приложение крупнейшего банка США: счета, переводы, оплата счетов, депозиты чеков и управление картами.',
    image: '/portfolio/chase.jpg',
    tags: ['Native iOS', 'Native Android', 'API'],
    link: 'https://www.chase.com',
    color: 'from-blue-700 to-blue-900',
    year: '2024',
    icon: '🏦',
    location: 'Нью-Йорк, США',
  },
  {
    id: 18,
    title: 'TD Bank',
    category: 'Банкинг',
    type: 'mobile',
    description: 'Мобильный банкинг одного из крупнейших банков Канады. Операции со счетами, переводы, инвестиции и поддержка 24/7.',
    image: '/portfolio/tdbank.jpg',
    tags: ['Swift', 'Kotlin', 'REST API'],
    link: 'https://www.td.com/ca/en/personal-banking',
    color: 'from-green-600 to-green-800',
    year: '2024',
    icon: '🍁',
    location: 'Торонто, Канада',
  },
  // Веб-сайты стоматологических клиник (США, Канада)
  {
    id: 19,
    title: 'Aspen Dental',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Сеть стоматологических клиник в США. Сайт с информацией об услугах, записью на приём, ценами и локациями по всей стране.',
    image: '/portfolio/aspen-dental.jpg',
    tags: ['React', 'Node.js', 'CMS'],
    link: 'https://www.aspendental.com',
    color: 'from-teal-600 to-cyan-600',
    year: '2024',
    icon: '🦷',
    location: 'США',
  },
  {
    id: 20,
    title: 'Dentalcorp',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Крупнейшая сеть стоматологических практик в Канаде. Сайт для пациентов: поиск клиники, услуги, запись онлайн и информация о лечении.',
    image: '/portfolio/dentalcorp.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'Booking'],
    link: 'https://www.dentalcorp.ca',
    color: 'from-blue-600 to-indigo-600',
    year: '2024',
    icon: '🦷',
    location: 'Торонто, Канада',
  },
  {
    id: 21,
    title: 'Coast Dental',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Сеть стоматологических офисов на юге США. Сайт с перечнем услуг, акциями, формой записи и контактами клиник.',
    image: '/portfolio/coast-dental.jpg',
    tags: ['HTML5', 'CSS', 'JavaScript'],
    link: 'https://www.coastdental.com',
    color: 'from-sky-500 to-blue-600',
    year: '2024',
    icon: '🦷',
    location: 'Флорида, США',
  },
  {
    id: 22,
    title: '123Dentist',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Канадская сеть стоматологических клиник. Поиск врача по городу, описание услуг, онлайн-запись и блог о здоровье зубов.',
    image: '/portfolio/123dentist.jpg',
    tags: ['Vue.js', 'Laravel', 'MySQL'],
    link: 'https://www.123dentist.com',
    color: 'from-emerald-600 to-teal-600',
    year: '2024',
    icon: '🦷',
    location: 'Ванкувер, Канада',
  },
]

/** Получить slug из внутренней ссылки /portfolio/xxx */
export function getSlugFromLink(link: string): string | null {
  if (link.startsWith('/portfolio/')) {
    return link.replace(/^\/portfolio\/?/, '').trim() || null
  }
  return null
}

export function getProjectBySlug(slug: string): PortfolioProject | undefined {
  return PORTFOLIO_PROJECTS.find((p) => getSlugFromLink(p.link) === slug)
}
