export type PortfolioProject = {
  id: number
  title: string
  category: string
  type: 'web' | 'mobile'
  description: string
  image: string
  tags: string[]
  link: string
  color: string
  year: string
  icon: string
  location: string
}

/** Порядок проектов на главной и в портфолио */
export const PORTFOLIO_PRIORITY_LINKS = [
  'https://ambadetail.by',
  'https://nexton.vip',
  'https://maxximum.by',
  'https://dynamovitebsk.by',
] as const

function normalizePortfolioLink(link: string): string {
  return link.replace(/\/+$/, '').toLowerCase()
}

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 3,
    title: 'Amba Detail',
    category: 'Детейлинг студия',
    type: 'web',
    description: 'Сайт студии детейлинга "Amba Detail" в Витебске. Услуги по профессиональному уходу за автомобилем: полировка, химчистка, керамическое покрытие, бронирование пленкой. Портфолио работ и прайс-лист.',
    image: '/portfolio/amba.png',
    tags: ['Next.js', 'Tailwind CSS', 'Node.js'],
    link: 'https://ambadetail.by',
    color: 'from-orange-600 to-red-500',
    year: '2026',
    icon: '🚘',
    location: 'Витебск',
  },
  {
    id: 23,
    title: 'nexton.vip',
    category: 'Корпоративный сайт',
    type: 'web',
    description: 'Сайт автосервиса NEXTON: заправка и ремонт кондиционеров, ремонт Webasto и систем охлаждения в Полоцке и Новополоцке.',
    image: '/portfolio/nexton.png',
    tags: ['Next.js', 'TypeScript', 'UI/UX'],
    link: 'https://nexton.vip',
    color: 'from-violet-600 to-fuchsia-600',
    year: '2026',
    icon: '💼',
    location: 'Полоцк',
  },
  {
    id: 2,
    title: 'Maxximum',
    category: 'Образование',
    type: 'web',
    description: 'Сайт спортивно-образовательного центра "Maxximum" в Витебске. Информация о направлениях подготовки, расписание занятий, тренерский состав и запись на пробные тренировки.',
    image: '/portfolio/maxximum.jpg',
    tags: ['React', 'TypeScript', 'Express'],
    link: 'https://maxximum.by',
    color: 'from-green-600 to-emerald-500',
    year: '2024',
    icon: '🏋️',
    location: 'Витебск',
  },
  {
    id: 1,
    title: 'Динамо-Витебск (СДЮШОР)',
    category: 'Спортивный сайт',
    type: 'web',
    description: 'Официальный сайт СДЮШОР "Динамо-Витебск". Информация о школе, отделения, спортивные секции, блог спортивной школы, достижения воспитанников и тренерский состав.',
    image: '/portfolio/dynamo.png',
    tags: ['Next.js', 'Tailwind CSS', 'Node.js'],
    link: 'https://dynamovitebsk.by',
    color: 'from-blue-600 to-cyan-500',
    year: '2019',
    icon: '🏒',
    location: 'Витебск',
  },
  {
    id: 24,
    title: 'BMservice',
    category: 'Автосервис',
    type: 'web',
    description: 'Сайт специализированного сервисного центра BMW, Mercedes и Land Rover в Витебске с описанием услуг, блогом и онлайн-записью.',
    image: '/portfolio/bmservice.jpg',
    tags: ['Next.js', 'SEO', 'UI/UX'],
    link: 'https://bmservice.by/',
    color: 'from-slate-700 to-gray-900',
    year: '2022',
    icon: '🔧',
    location: 'Витебск',
  },
  // Отрасль: Производство (США, Канада, Нидерланды, Индия, Китай)
  {
    id: 25,
    title: 'Emerson',
    category: 'Производство',
    type: 'web',
    description: 'Корпоративный сайт промышленной компании с каталогом решений для автоматизации производства.',
    image: '/portfolio/emerson.jpg',
    tags: ['Next.js', 'B2B', 'Corporate'],
    link: 'https://www.emerson.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'США',
  },
  {
    id: 26,
    title: 'Magna International',
    category: 'Производство',
    type: 'web',
    description: 'Сайт международного производителя компонентов для автомобильной промышленности.',
    image: '/portfolio/magna.jpg',
    tags: ['React', 'B2B', 'Manufacturing'],
    link: 'https://www.magna.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'Канада',
  },
  {
    id: 27,
    title: 'ASML',
    category: 'Производство',
    type: 'web',
    description: 'Технологический сайт компании-производителя оборудования для полупроводниковой отрасли.',
    image: '/portfolio/asml.jpg',
    tags: ['Next.js', 'Tech', 'Enterprise'],
    link: 'https://www.asml.com',
    color: 'from-slate-600 to-gray-800',
    year: '2025',
    icon: '🏭',
    location: 'Нидерланды',
  },
  {
    id: 28,
    title: 'Tata Steel',
    category: 'Производство',
    type: 'web',
    description: 'Корпоративный веб-ресурс металлургической компании с отраслевыми решениями и ESG-разделами.',
    image: '/portfolio/tata-steel.jpg',
    tags: ['React', 'CSR', 'Enterprise'],
    link: 'https://www.tatasteel.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'Индия',
  },
  {
    id: 29,
    title: 'SANY Group',
    category: 'Производство',
    type: 'web',
    description: 'Сайт производителя строительной и промышленной техники для международного рынка.',
    image: '/portfolio/sany.jpg',
    tags: ['Vue.js', 'Industrial', 'Global'],
    link: 'https://www.sanyglobal.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'Китай',
  },

  // Отрасль: Финансы
  {
    id: 30,
    title: 'JPMorgan Chase',
    category: 'Финансы',
    type: 'web',
    description: 'Финансовый портал с банковскими продуктами, инвест-сервисами и клиентскими кабинетами.',
    image: '/portfolio/jpmorgan.jpg',
    tags: ['Fintech', 'Security', 'Enterprise'],
    link: 'https://www.jpmorganchase.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'США',
  },
  {
    id: 31,
    title: 'RBC',
    category: 'Финансы',
    type: 'web',
    description: 'Сайт банка с услугами для частных и корпоративных клиентов и онлайн-банкингом.',
    image: '/portfolio/rbc.jpg',
    tags: ['Banking', 'React', 'Security'],
    link: 'https://www.rbcroyalbank.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2025',
    icon: '🏦',
    location: 'Канада',
  },
  {
    id: 32,
    title: 'ING',
    category: 'Финансы',
    type: 'web',
    description: 'Финансовый сайт с цифровыми сервисами, продуктами кредитования и инвестиционными инструментами.',
    image: '/portfolio/ing.jpg',
    tags: ['Banking', 'Digital', 'UX'],
    link: 'https://www.ing.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'Нидерланды',
  },
  {
    id: 33,
    title: 'HDFC Bank',
    category: 'Финансы',
    type: 'web',
    description: 'Банковский портал с продуктами для физических лиц, бизнеса и цифровыми платежами.',
    image: '/portfolio/hdfc.jpg',
    tags: ['Banking', 'Payments', 'Enterprise'],
    link: 'https://www.hdfcbank.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'Индия',
  },
  {
    id: 34,
    title: 'ICBC',
    category: 'Финансы',
    type: 'web',
    description: 'Сайт крупнейшего банка с международными банковскими и инвестиционными сервисами.',
    image: '/portfolio/icbc.jpg',
    tags: ['Banking', 'Enterprise', 'Global'],
    link: 'https://www.icbc.com.cn',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'Китай',
  },

  // Отрасль: Медицина
  {
    id: 35,
    title: 'Mayo Clinic',
    category: 'Медицина',
    type: 'web',
    description: 'Медицинский портал с сервисами записи, справочником услуг и образовательным контентом.',
    image: '/portfolio/mayo-clinic.jpg',
    tags: ['Healthcare', 'UX', 'Accessibility'],
    link: 'https://www.mayoclinic.org',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'США',
  },
  {
    id: 36,
    title: 'UHN',
    category: 'Медицина',
    type: 'web',
    description: 'Сайт университетской медицинской сети с информацией для пациентов и клиническими программами.',
    image: '/portfolio/uhn.jpg',
    tags: ['Healthcare', 'Next.js', 'Content'],
    link: 'https://www.uhn.ca',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'Канада',
  },
  {
    id: 37,
    title: 'Philips Healthcare',
    category: 'Медицина',
    type: 'web',
    description: 'Веб-платформа медицинских технологий и решений для клиник и диагностических центров.',
    image: '/portfolio/philips-health.jpg',
    tags: ['MedTech', 'B2B', 'Enterprise'],
    link: 'https://www.philips.com/healthcare',
    color: 'from-teal-600 to-cyan-700',
    year: '2025',
    icon: '🏥',
    location: 'Нидерланды',
  },
  {
    id: 38,
    title: 'Apollo Hospitals',
    category: 'Медицина',
    type: 'web',
    description: 'Сайт сети клиник с онлайн-записью, услугами диагностики и информацией для пациентов.',
    image: '/portfolio/apollo.jpg',
    tags: ['Healthcare', 'Booking', 'SEO'],
    link: 'https://www.apollohospitals.com',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'Индия',
  },
  {
    id: 39,
    title: 'Ping An Good Doctor',
    category: 'Медицина',
    type: 'web',
    description: 'Платформа цифровой медицины с сервисами консультаций и управлением здоровьем онлайн.',
    image: '/portfolio/pingan.jpg',
    tags: ['Digital Health', 'Telemedicine', 'Platform'],
    link: 'https://www.pagd.net',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'Китай',
  },

  // Отрасль: Ритейл
  {
    id: 40,
    title: 'Walmart',
    category: 'Ритейл',
    type: 'web',
    description: 'Крупный e-commerce сайт ритейлера с каталогом, доставкой и персональными рекомендациями.',
    image: '/portfolio/walmart.jpg',
    tags: ['E-commerce', 'Retail', 'UX'],
    link: 'https://www.walmart.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'США',
  },
  {
    id: 41,
    title: 'Canadian Tire',
    category: 'Ритейл',
    type: 'web',
    description: 'Онлайн-витрина сети магазинов с программой лояльности и омниканальными продажами.',
    image: '/portfolio/canadian-tire.jpg',
    tags: ['Retail', 'Loyalty', 'E-commerce'],
    link: 'https://www.canadiantire.ca',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'Канада',
  },
  {
    id: 42,
    title: 'Ahold Delhaize',
    category: 'Ритейл',
    type: 'web',
    description: 'Корпоративный ритейл-портал с брендами, цифровыми сервисами и отчетами для инвесторов.',
    image: '/portfolio/ahold.jpg',
    tags: ['Retail', 'Corporate', 'Content'],
    link: 'https://www.aholddelhaize.com',
    color: 'from-purple-600 to-pink-600',
    year: '2025',
    icon: '🛍️',
    location: 'Нидерланды',
  },
  {
    id: 43,
    title: 'Reliance Retail',
    category: 'Ритейл',
    type: 'web',
    description: 'Сайт одного из крупнейших ритейлеров с омниканальными продуктами и цифровыми сервисами.',
    image: '/portfolio/reliance-retail.jpg',
    tags: ['Retail', 'Omnichannel', 'Digital'],
    link: 'https://relianceretail.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'Индия',
  },
  {
    id: 44,
    title: 'JD.com',
    category: 'Ритейл',
    type: 'web',
    description: 'Маркетплейс с широкой логистической инфраструктурой и развитой экосистемой e-commerce.',
    image: '/portfolio/jd.jpg',
    tags: ['Marketplace', 'E-commerce', 'Scale'],
    link: 'https://www.jd.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'Китай',
  },

  // Отрасль: Логистика
  {
    id: 45,
    title: 'UPS',
    category: 'Логистика',
    type: 'web',
    description: 'Логистический портал с отслеживанием отправлений, калькулятором доставки и сервисами для бизнеса.',
    image: '/portfolio/ups.jpg',
    tags: ['Logistics', 'Tracking', 'B2B'],
    link: 'https://www.ups.com',
    color: 'from-amber-600 to-yellow-700',
    year: '2024',
    icon: '🚚',
    location: 'США',
  },
  {
    id: 46,
    title: 'Purolator',
    category: 'Логистика',
    type: 'web',
    description: 'Сайт курьерской службы с инструментами отслеживания и решениями для e-commerce доставки.',
    image: '/portfolio/purolator.jpg',
    tags: ['Logistics', 'Delivery', 'E-commerce'],
    link: 'https://www.purolator.com',
    color: 'from-amber-600 to-yellow-700',
    year: '2024',
    icon: '🚚',
    location: 'Канада',
  },
  {
    id: 47,
    title: 'PostNL',
    category: 'Логистика',
    type: 'web',
    description: 'Почтово-логистический сервис с управлением отправлениями и клиентскими кабинетами.',
    image: '/portfolio/postnl.jpg',
    tags: ['Logistics', 'Postal', 'Digital'],
    link: 'https://www.postnl.nl',
    color: 'from-amber-600 to-yellow-700',
    year: '2025',
    icon: '🚚',
    location: 'Нидерланды',
  },
  {
    id: 48,
    title: 'Delhivery',
    category: 'Логистика',
    type: 'web',
    description: 'Логистическая платформа для бизнеса с доставкой, фулфилментом и API-интеграциями.',
    image: '/portfolio/delhivery.jpg',
    tags: ['Logistics', 'API', 'Platform'],
    link: 'https://www.delhivery.com',
    color: 'from-amber-600 to-yellow-700',
    year: '2024',
    icon: '🚚',
    location: 'Индия',
  },
  {
    id: 49,
    title: 'SF Express',
    category: 'Логистика',
    type: 'web',
    description: 'Международный логистический портал с тарифами, трекингом и корпоративными решениями.',
    image: '/portfolio/sf-express.jpg',
    tags: ['Logistics', 'Enterprise', 'Tracking'],
    link: 'https://www.sf-express.com',
    color: 'from-amber-600 to-yellow-700',
    year: '2024',
    icon: '🚚',
    location: 'Китай',
  },

  // Отрасль: Образование
  {
    id: 50,
    title: 'Coursera',
    category: 'Образование',
    type: 'web',
    description: 'EdTech-платформа с онлайн-курсами, специализациями и профессиональными сертификатами.',
    image: '/portfolio/coursera.jpg',
    tags: ['EdTech', 'Platform', 'UX'],
    link: 'https://www.coursera.org',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'США',
  },
  {
    id: 51,
    title: 'University of Toronto',
    category: 'Образование',
    type: 'web',
    description: 'Университетский портал с программами обучения, исследовательскими проектами и новостями.',
    image: '/portfolio/utoronto.jpg',
    tags: ['Education', 'Content', 'Accessibility'],
    link: 'https://www.utoronto.ca',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'Канада',
  },
  {
    id: 52,
    title: 'TU Delft',
    category: 'Образование',
    type: 'web',
    description: 'Портал технического университета с образовательными программами и научными инициативами.',
    image: '/portfolio/tudelft.jpg',
    tags: ['Education', 'University', 'UX'],
    link: 'https://www.tudelft.nl',
    color: 'from-indigo-600 to-blue-700',
    year: '2025',
    icon: '📚',
    location: 'Нидерланды',
  },
  {
    id: 53,
    title: 'BYJU’S',
    category: 'Образование',
    type: 'web',
    description: 'Образовательная платформа с цифровыми курсами для школьников и студентов.',
    image: '/portfolio/byjus.jpg',
    tags: ['EdTech', 'Learning', 'Mobile-first'],
    link: 'https://byjus.com',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'Индия',
  },
  {
    id: 54,
    title: 'Tsinghua University',
    category: 'Образование',
    type: 'web',
    description: 'Университетский веб-сайт с академическими программами, научными публикациями и новостями.',
    image: '/portfolio/tsinghua.jpg',
    tags: ['Education', 'University', 'Research'],
    link: 'https://www.tsinghua.edu.cn',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'Китай',
  },

  // Отрасль: Энергетика
  {
    id: 55,
    title: 'NextEra Energy',
    category: 'Энергетика',
    type: 'web',
    description: 'Сайт энергетической компании с решениями в области возобновляемой и традиционной энергетики.',
    image: '/portfolio/nextera.jpg',
    tags: ['Energy', 'Corporate', 'Sustainability'],
    link: 'https://www.nexteraenergy.com',
    color: 'from-emerald-600 to-green-700',
    year: '2024',
    icon: '⚡',
    location: 'США',
  },
  {
    id: 56,
    title: 'Enbridge',
    category: 'Энергетика',
    type: 'web',
    description: 'Корпоративный портал энергетической инфраструктуры с сервисами и отчетностью.',
    image: '/portfolio/enbridge.jpg',
    tags: ['Energy', 'Infrastructure', 'B2B'],
    link: 'https://www.enbridge.com',
    color: 'from-emerald-600 to-green-700',
    year: '2024',
    icon: '⚡',
    location: 'Канада',
  },
  {
    id: 57,
    title: 'Shell',
    category: 'Энергетика',
    type: 'web',
    description: 'Сайт международной энергетической компании с разделами для бизнеса, инвесторов и ESG.',
    image: '/portfolio/shell.jpg',
    tags: ['Energy', 'Corporate', 'Global'],
    link: 'https://www.shell.com',
    color: 'from-emerald-600 to-green-700',
    year: '2025',
    icon: '⚡',
    location: 'Нидерланды',
  },
  {
    id: 58,
    title: 'Tata Power',
    category: 'Энергетика',
    type: 'web',
    description: 'Энергетический портал с решениями для частных клиентов и корпоративного сегмента.',
    image: '/portfolio/tata-power.jpg',
    tags: ['Energy', 'Utilities', 'Digital'],
    link: 'https://www.tatapower.com',
    color: 'from-emerald-600 to-green-700',
    year: '2024',
    icon: '⚡',
    location: 'Индия',
  },
  {
    id: 59,
    title: 'State Grid',
    category: 'Энергетика',
    type: 'web',
    description: 'Сайт энергетической компании с сервисами распределения электроэнергии и отраслевыми решениями.',
    image: '/portfolio/state-grid.jpg',
    tags: ['Energy', 'Grid', 'Enterprise'],
    link: 'http://www.sgcc.com.cn',
    color: 'from-emerald-600 to-green-700',
    year: '2024',
    icon: '⚡',
    location: 'Китай',
  },

  // Отрасль: Развлечения
  {
    id: 60,
    title: 'Netflix',
    category: 'Развлечения',
    type: 'web',
    description: 'Стриминговая платформа с персонализацией контента, рекомендациями и мультиязычным интерфейсом.',
    image: '/portfolio/netflix.jpg',
    tags: ['Streaming', 'Personalization', 'Platform'],
    link: 'https://www.netflix.com',
    color: 'from-rose-600 to-red-700',
    year: '2024',
    icon: '🎮',
    location: 'США',
  },
  {
    id: 61,
    title: 'Cineplex',
    category: 'Развлечения',
    type: 'web',
    description: 'Сайт сети кинотеатров с расписанием, продажей билетов и программами лояльности.',
    image: '/portfolio/cineplex.jpg',
    tags: ['Entertainment', 'Tickets', 'UX'],
    link: 'https://www.cineplex.com',
    color: 'from-rose-600 to-red-700',
    year: '2024',
    icon: '🎮',
    location: 'Канада',
  },
  {
    id: 62,
    title: 'Pathé Netherlands',
    category: 'Развлечения',
    type: 'web',
    description: 'Кинопортал с афишей, билетами, личным кабинетом и сервисами для посетителей.',
    image: '/portfolio/pathe.jpg',
    tags: ['Cinema', 'Booking', 'Digital'],
    link: 'https://www.pathe.nl',
    color: 'from-rose-600 to-red-700',
    year: '2025',
    icon: '🎮',
    location: 'Нидерланды',
  },
  {
    id: 63,
    title: 'BookMyShow',
    category: 'Развлечения',
    type: 'web',
    description: 'Платформа бронирования билетов на кино, концерты и мероприятия.',
    image: '/portfolio/bookmyshow.jpg',
    tags: ['Tickets', 'Events', 'Platform'],
    link: 'https://in.bookmyshow.com',
    color: 'from-rose-600 to-red-700',
    year: '2024',
    icon: '🎮',
    location: 'Индия',
  },
  {
    id: 64,
    title: 'Tencent Video',
    category: 'Развлечения',
    type: 'web',
    description: 'Видео-платформа с каталогом сериалов, фильмов и оригинального контента.',
    image: '/portfolio/tencent-video.jpg',
    tags: ['Streaming', 'Video', 'Platform'],
    link: 'https://v.qq.com',
    color: 'from-rose-600 to-red-700',
    year: '2024',
    icon: '🎮',
    location: 'Китай',
  },

  // Отрасль: Консалтинг
  {
    id: 65,
    title: 'McKinsey & Company',
    category: 'Консалтинг',
    type: 'web',
    description: 'Корпоративный сайт консалтинговой компании с кейсами, исследованиями и отраслевой экспертизой.',
    image: '/portfolio/mckinsey.jpg',
    tags: ['Consulting', 'Corporate', 'Content'],
    link: 'https://www.mckinsey.com',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'США',
  },
  {
    id: 66,
    title: 'Deloitte Canada',
    category: 'Консалтинг',
    type: 'web',
    description: 'Сайт консалтинговой и аудиторской компании с бизнес-услугами и аналитикой.',
    image: '/portfolio/deloitte-ca.jpg',
    tags: ['Consulting', 'Audit', 'Enterprise'],
    link: 'https://www2.deloitte.com/ca/en.html',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'Канада',
  },
  {
    id: 67,
    title: 'BCG Netherlands',
    category: 'Консалтинг',
    type: 'web',
    description: 'Веб-представительство консалтинговой компании с отраслевой аналитикой и экспертизой.',
    image: '/portfolio/bcg.jpg',
    tags: ['Consulting', 'Strategy', 'Insights'],
    link: 'https://www.bcg.com',
    color: 'from-sky-700 to-blue-900',
    year: '2025',
    icon: '📊',
    location: 'Нидерланды',
  },
  {
    id: 68,
    title: 'Infosys Consulting',
    category: 'Консалтинг',
    type: 'web',
    description: 'Сайт консалтингового подразделения с услугами цифровой трансформации для бизнеса.',
    image: '/portfolio/infosys.jpg',
    tags: ['Consulting', 'Digital', 'Transformation'],
    link: 'https://www.infosys.com/services/consulting',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'Индия',
  },
  {
    id: 69,
    title: 'Accenture China',
    category: 'Консалтинг',
    type: 'web',
    description: 'Сайт консалтинговой компании с решениями в области стратегии, технологий и операций.',
    image: '/portfolio/accenture-cn.jpg',
    tags: ['Consulting', 'Technology', 'Enterprise'],
    link: 'https://www.accenture.cn',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'Китай',
  },
  {
    id: 4,
    title: 'Sparkite',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Реабилитационное приложение для бывших пациентов. Помогает вернуться к здоровому образу жизни через постановку целей и ежедневные чекины.',
    image: '/portfolio/sparkite.jpg',
    tags: ['React Native', 'Node.js', 'PostgreSQL'],
    link: '/portfolio/sparkite',
    color: 'from-purple-600 to-pink-500',
    year: '2024',
    icon: '🧘',
    location: 'Нью-Йорк, США',
  },
  {
    id: 5,
    title: 'Buzz',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Приложение для поиска и организации ивентов в небольших американских городах с уникальной системой рекомендаций.',
    image: '/portfolio/buzz.jpg',
    tags: ['Flutter', 'Firebase', 'Google Maps API'],
    link: '/portfolio/buzz',
    color: 'from-yellow-500 to-orange-500',
    year: '2025',
    icon: '🎉',
    location: 'США',
  },
  {
    id: 6,
    title: 'Erin Wesley',
    category: 'Веб-сайт',
    type: 'web',
    description: 'Сайт-портфолио для оператора-постановщика с уникальными GLSL-анимациями и кастомным скроллом.',
    image: '/portfolio/erin.jpg',
    tags: ['Next.js', 'Three.js', 'GSAP'],
    link: '/portfolio/erin',
    color: 'from-indigo-600 to-purple-500',
    year: '2023',
    icon: '🎬',
    location: 'Лос-Анджелес, США',
  },
  {
    id: 7,
    title: 'VSE NASHI',
    category: 'Мобильное приложение',
    type: 'mobile',
    description: 'Социальная платформа для русскоязычной диаспоры в США: работа, знакомства, услуги и события.',
    image: '/portfolio/vsenashi.jpg',
    tags: ['React Native', 'Node.js', 'MongoDB'],
    link: '/portfolio/vsenashi',
    color: 'from-teal-500 to-green-500',
    year: '2025',
    icon: '🌎',
    location: 'США',
  },
  {
    id: 8,
    title: 'Vigbo',
    category: 'Веб-платформа',
    type: 'web',
    description: 'Конструктор сайтов для творцов и предпринимателей с системой клиентских галерей.',
    image: '/portfolio/vigbo.jpg',
    tags: ['Vue.js', 'Node.js', 'AWS'],
    link: '/portfolio/vigbo',
    color: 'from-pink-500 to-rose-500',
    year: '2024',
    icon: '✨',
    location: 'Уэстон, Флорида, США',
  },
  // Веб-разработка: интернет-магазины и консалтинг (США и Канада)
  {
    id: 9,
    title: 'Taylor Stitch',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Онлайн-магазин мужской одежды и аксессуаров. Каталог, корзина, примерка и доставка по США. Адаптивный дизайн и удобный поиск.',
    image: '/portfolio/taylorstitch.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'E-commerce'],
    link: 'https://www.taylorstitch.com',
    color: 'from-amber-700 to-amber-900',
    year: '2024',
    icon: '👔',
    location: 'Сан-Франциско, США',
  },
  {
    id: 10,
    title: 'Altitude Sports',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Канадский интернет-магазин одежды и снаряжения для спорта и активного отдыха. Каталог брендов, фильтры и доставка по Канаде.',
    image: '/portfolio/altitude.jpg',
    tags: ['React', 'Node.js', 'E-commerce'],
    link: 'https://www.altitude-sports.com',
    color: 'from-sky-600 to-blue-700',
    year: '2024',
    icon: '🏔️',
    location: 'Монреаль, Канада',
  },
  {
    id: 11,
    title: 'Huckberry',
    category: 'Интернет-магазин',
    type: 'web',
    description: 'Онлайн-магазин товаров для путешествий, одежды и экипировки. Удобный каталог, рекомендации и доставка по США.',
    image: '/portfolio/huckberry.jpg',
    tags: ['Shopify', 'Liquid', 'JavaScript'],
    link: 'https://www.huckberry.com',
    color: 'from-stone-700 to-stone-900',
    year: '2024',
    icon: '🎒',
    location: 'Остин, США',
  },
  {
    id: 12,
    title: 'Slalom',
    category: 'Консалтинговые услуги',
    type: 'web',
    description: 'Сайт консалтинговой компании: стратегия, цифровая трансформация и разработка. Презентация услуг, кейсы и контакты для бизнеса в США.',
    image: '/portfolio/slalom.jpg',
    tags: ['React', 'Contentful', 'AWS'],
    link: 'https://www.slalom.com',
    color: 'from-blue-700 to-indigo-800',
    year: '2024',
    icon: '📊',
    location: 'Сиэтл, США',
  },
  {
    id: 13,
    title: 'CGI',
    category: 'Консалтинговые услуги',
    type: 'web',
    description: 'Сайт канадской IT- и бизнес-консалтинговой компании. Услуги по цифровизации, интеграции и аутсорсингу для предприятий в Канаде и мире.',
    image: '/portfolio/cgi.jpg',
    tags: ['HTML5', 'CSS', 'JavaScript'],
    link: 'https://www.cgi.com/en',
    color: 'from-red-600 to-rose-700',
    year: '2024',
    icon: '🍁',
    location: 'Монреаль, Канада',
  },
  // Мобильные приложения: фитнес и банкинг (США, Канада)
  {
    id: 14,
    title: 'Strava',
    category: 'Фитнес-приложение',
    type: 'mobile',
    description: 'Приложение для бега, велоспорта и трекинга тренировок. Маршруты, статистика, челленджи и социальная лента для атлетов в США и мире.',
    image: '/portfolio/strava.jpg',
    tags: ['React Native', 'Node.js', 'PostgreSQL'],
    link: 'https://www.strava.com',
    color: 'from-orange-500 to-orange-700',
    year: '2024',
    icon: '🏃',
    location: 'Сан-Франциско, США',
  },
  {
    id: 15,
    title: 'Peloton',
    category: 'Фитнес-приложение',
    type: 'mobile',
    description: 'Мобильное приложение для домашних тренировок: вело- и беговые дорожки, йога, силовые. Живые и записанные занятия с тренерами.',
    image: '/portfolio/peloton.jpg',
    tags: ['React Native', 'Swift', 'Kotlin'],
    link: 'https://www.onepeloton.com',
    color: 'from-gray-900 to-black',
    year: '2024',
    icon: '🚴',
    location: 'Нью-Йорк, США',
  },
  {
    id: 17,
    title: 'Chase Mobile',
    category: 'Банкинг',
    type: 'mobile',
    description: 'Мобильное приложение крупнейшего банка США: счета, переводы, оплата счетов, депозиты чеков и управление картами.',
    image: '/portfolio/chase.jpg',
    tags: ['Native iOS', 'Native Android', 'API'],
    link: 'https://www.chase.com',
    color: 'from-blue-700 to-blue-900',
    year: '2024',
    icon: '🏦',
    location: 'Нью-Йорк, США',
  },
  {
    id: 18,
    title: 'TD Bank',
    category: 'Банкинг',
    type: 'mobile',
    description: 'Мобильный банкинг одного из крупнейших банков Канады. Операции со счетами, переводы, инвестиции и поддержка 24/7.',
    image: '/portfolio/tdbank.jpg',
    tags: ['Swift', 'Kotlin', 'REST API'],
    link: 'https://www.td.com/ca/en/personal-banking',
    color: 'from-green-600 to-green-800',
    year: '2024',
    icon: '🍁',
    location: 'Торонто, Канада',
  },
  // Веб-сайты стоматологических клиник (США, Канада)
  {
    id: 19,
    title: 'Aspen Dental',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Сеть стоматологических клиник в США. Сайт с информацией об услугах, записью на приём, ценами и локациями по всей стране.',
    image: '/portfolio/aspen-dental.jpg',
    tags: ['React', 'Node.js', 'CMS'],
    link: 'https://www.aspendental.com',
    color: 'from-teal-600 to-cyan-600',
    year: '2024',
    icon: '🦷',
    location: 'США',
  },
  {
    id: 20,
    title: 'Dentalcorp',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Крупнейшая сеть стоматологических практик в Канаде. Сайт для пациентов: поиск клиники, услуги, запись онлайн и информация о лечении.',
    image: '/portfolio/dentalcorp.jpg',
    tags: ['Next.js', 'Tailwind CSS', 'Booking'],
    link: 'https://www.dentalcorp.ca',
    color: 'from-blue-600 to-indigo-600',
    year: '2024',
    icon: '🦷',
    location: 'Торонто, Канада',
  },
  {
    id: 21,
    title: 'Coast Dental',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Сеть стоматологических офисов на юге США. Сайт с перечнем услуг, акциями, формой записи и контактами клиник.',
    image: '/portfolio/coast-dental.jpg',
    tags: ['HTML5', 'CSS', 'JavaScript'],
    link: 'https://www.coastdental.com',
    color: 'from-sky-500 to-blue-600',
    year: '2024',
    icon: '🦷',
    location: 'Флорида, США',
  },
  {
    id: 22,
    title: '123Dentist',
    category: 'Стоматологическая клиника',
    type: 'web',
    description: 'Канадская сеть стоматологических клиник. Поиск врача по городу, описание услуг, онлайн-запись и блог о здоровье зубов.',
    image: '/portfolio/123dentist.jpg',
    tags: ['Vue.js', 'Laravel', 'MySQL'],
    link: 'https://www.123dentist.com',
    color: 'from-emerald-600 to-teal-600',
    year: '2024',
    icon: '🦷',
    location: 'Ванкувер, Канада',
  },
  // ---- Дополнительные проекты по отраслям (5-20 в каждом разделе) ----
  // Производство
  {
    id: 70,
    title: 'Boeing',
    category: 'Производство',
    type: 'web',
    description: 'Корпоративный сайт авиационного производителя: продуктовые направления, новости и инвесторские материалы.',
    image: '/portfolio/boeing.jpg',
    tags: ['Enterprise', 'Corporate', 'Global'],
    link: 'https://www.boeing.com',
    color: 'from-slate-600 to-gray-800',
    year: '2025',
    icon: '🏭',
    location: 'США',
  },
  {
    id: 71,
    title: 'Caterpillar',
    category: 'Производство',
    type: 'web',
    description: 'Промышленная экосистема: продукты, сервисы и цифровые решения для строительной техники.',
    image: '/portfolio/caterpillar.jpg',
    tags: ['Industrial', 'B2B', 'Digital'],
    link: 'https://www.caterpillar.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'США',
  },
  {
    id: 72,
    title: 'Honeywell',
    category: 'Производство',
    type: 'web',
    description: 'Сайт технологического концерна для индустрии: автоматизация, решения для производств и корпоративный контент.',
    image: '/portfolio/honeywell.jpg',
    tags: ['Automation', 'B2B', 'Enterprise'],
    link: 'https://www.honeywell.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'США',
  },
  {
    id: 73,
    title: 'Tesla',
    category: 'Производство',
    type: 'web',
    description: 'Корпоративный цифровой ресурс производителя: продуктовые линейки, обновления и медиа-материалы.',
    image: '/portfolio/tesla.jpg',
    tags: ['Electric', 'Products', 'Corporate'],
    link: 'https://www.tesla.com',
    color: 'from-slate-600 to-gray-800',
    year: '2025',
    icon: '🏭',
    location: 'США',
  },
  {
    id: 74,
    title: '3M',
    category: 'Производство',
    type: 'web',
    description: 'Промышленный гигант: решения для отраслей, каталоги продуктов и корпоративная информация.',
    image: '/portfolio/3m.jpg',
    tags: ['Enterprise', 'Catalog', 'Manufacturing'],
    link: 'https://www.3m.com',
    color: 'from-slate-600 to-gray-800',
    year: '2024',
    icon: '🏭',
    location: 'США',
  },

  // Финансы
  {
    id: 75,
    title: 'Bank of America',
    category: 'Финансы',
    type: 'web',
    description: 'Финансовая витрина: банковские сервисы, инвестиционные предложения и цифровые инструменты.',
    image: '/portfolio/bank-of-america.jpg',
    tags: ['Banking', 'UX', 'Enterprise'],
    link: 'https://www.bankofamerica.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'США',
  },
  {
    id: 76,
    title: 'Scotiabank',
    category: 'Финансы',
    type: 'web',
    description: 'Клиентский онлайн-сервис банка: продукты, управление счетами и цифровые продукты.',
    image: '/portfolio/scotiabank.jpg',
    tags: ['Banking', 'Security', 'Digital'],
    link: 'https://www.scotiabank.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'Канада',
  },
  {
    id: 77,
    title: 'Rabobank',
    category: 'Финансы',
    type: 'web',
    description: 'Банковский ресурс с цифровыми продуктами для частных и корпоративных клиентов.',
    image: '/portfolio/rabobank.jpg',
    tags: ['Banking', 'Corporate', 'UX'],
    link: 'https://www.rabobank.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2025',
    icon: '🏦',
    location: 'Нидерланды',
  },
  {
    id: 78,
    title: 'ICICI Bank',
    category: 'Финансы',
    type: 'web',
    description: 'Цифровая платформа банка: платежи, сервисы для бизнеса и продукты для клиентов.',
    image: '/portfolio/icici-bank.jpg',
    tags: ['Banking', 'Payments', 'Enterprise'],
    link: 'https://www.icicibank.com',
    color: 'from-blue-700 to-indigo-900',
    year: '2024',
    icon: '🏦',
    location: 'Индия',
  },

  // Медицина
  {
    id: 79,
    title: 'Johns Hopkins Medicine',
    category: 'Медицина',
    type: 'web',
    description: 'Медицинский портал с сервисами записи, клиническими направлениями и пациентской информацией.',
    image: '/portfolio/johns-hopkins.jpg',
    tags: ['Healthcare', 'Patients', 'Information'],
    link: 'https://www.hopkinsmedicine.org',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'США',
  },
  {
    id: 80,
    title: 'Cleveland Clinic',
    category: 'Медицина',
    type: 'web',
    description: 'Сайт клиники: услуги, направления лечения и образовательный контент для пациентов.',
    image: '/portfolio/cleveland-clinic.jpg',
    tags: ['Healthcare', 'Care', 'UX'],
    link: 'https://my.clevelandclinic.org',
    color: 'from-teal-600 to-cyan-700',
    year: '2025',
    icon: '🏥',
    location: 'США',
  },
  {
    id: 81,
    title: 'Erasmus MC',
    category: 'Медицина',
    type: 'web',
    description: 'Научно-клинический портал: исследования, клинические программы и услуги для пациентов.',
    image: '/portfolio/erasmus-mc.jpg',
    tags: ['Healthcare', 'Research', 'Enterprise'],
    link: 'https://www.erasmusmc.nl',
    color: 'from-teal-600 to-cyan-700',
    year: '2024',
    icon: '🏥',
    location: 'Нидерланды',
  },

  // Ритейл
  {
    id: 82,
    title: 'Target',
    category: 'Ритейл',
    type: 'web',
    description: 'Магазин и витрина ритейлера: ассортимент, сервисы покупок и персональные рекомендации.',
    image: '/portfolio/target.jpg',
    tags: ['E-commerce', 'Retail', 'UX'],
    link: 'https://www.target.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'США',
  },
  {
    id: 83,
    title: 'Best Buy',
    category: 'Ритейл',
    type: 'web',
    description: 'E-commerce ритейлера электроники: каталог, акции и удобные сценарии покупки.',
    image: '/portfolio/best-buy.jpg',
    tags: ['E-commerce', 'Electronics', 'Conversion'],
    link: 'https://www.bestbuy.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'США',
  },
  {
    id: 84,
    title: 'Costco',
    category: 'Ритейл',
    type: 'web',
    description: 'Корпоративно-розничный сайт ритейлера: каталог, доставка и сервисы для участников.',
    image: '/portfolio/costco.jpg',
    tags: ['Retail', 'Catalog', 'UX'],
    link: 'https://www.costco.com',
    color: 'from-purple-600 to-pink-600',
    year: '2025',
    icon: '🛍️',
    location: 'США',
  },
  {
    id: 85,
    title: 'Bol.com',
    category: 'Ритейл',
    type: 'web',
    description: 'Маркетплейс в Нидерландах: подбор товаров, заказ и цифровые сервисы.',
    image: '/portfolio/bol-com.jpg',
    tags: ['Marketplace', 'E-commerce', 'Search'],
    link: 'https://www.bol.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'Нидерланды',
  },
  {
    id: 86,
    title: 'Flipkart',
    category: 'Ритейл',
    type: 'web',
    description: 'Крупный индийский маркетплейс: ассортимент, логистика и витрина продавцов.',
    image: '/portfolio/flipkart.jpg',
    tags: ['Marketplace', 'E-commerce', 'Scale'],
    link: 'https://www.flipkart.com',
    color: 'from-purple-600 to-pink-600',
    year: '2024',
    icon: '🛍️',
    location: 'Индия',
  },

  // Логистика
  {
    id: 87,
    title: 'FedEx',
    category: 'Логистика',
    type: 'web',
    description: 'Логистический сервис: трекинг отправлений, расчеты доставки и инструменты для бизнеса.',
    image: '/portfolio/fedex.jpg',
    tags: ['Logistics', 'Tracking', 'Enterprise'],
    link: 'https://www.fedex.com',
    color: 'from-amber-600 to-yellow-700',
    year: '2024',
    icon: '🚚',
    location: 'США',
  },
  {
    id: 88,
    title: 'Canada Post',
    category: 'Логистика',
    type: 'web',
    description: 'Почтово-логистический портал: тарифы, трекинг и услуги доставки по стране.',
    image: '/portfolio/canada-post.jpg',
    tags: ['Postal', 'Logistics', 'Services'],
    link: 'https://www.canadapost-postescanada.ca',
    color: 'from-amber-600 to-yellow-700',
    year: '2025',
    icon: '🚚',
    location: 'Канада',
  },

  // Образование
  {
    id: 89,
    title: 'Khan Academy',
    category: 'Образование',
    type: 'web',
    description: 'EdTech платформа: курсы, персональные рекомендации и образовательные материалы.',
    image: '/portfolio/khan-academy.jpg',
    tags: ['EdTech', 'Learning', 'Platform'],
    link: 'https://www.khanacademy.org',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'США',
  },
  {
    id: 90,
    title: 'edX',
    category: 'Образование',
    type: 'web',
    description: 'Платформа онлайн-курсов: каталог программ, треки обучения и профессиональные сертификаты.',
    image: '/portfolio/edx.jpg',
    tags: ['EdTech', 'Courses', 'Content'],
    link: 'https://www.edx.org',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'США',
  },
  {
    id: 91,
    title: 'Harvard University',
    category: 'Образование',
    type: 'web',
    description: 'Официальный университетский портал: новости, программы обучения, исследования и события.',
    image: '/portfolio/harvard.jpg',
    tags: ['University', 'Content', 'Enterprise'],
    link: 'https://www.harvard.edu',
    color: 'from-indigo-600 to-blue-700',
    year: '2025',
    icon: '📚',
    location: 'США',
  },
  {
    id: 92,
    title: 'Stanford University',
    category: 'Образование',
    type: 'web',
    description: 'Портал Стэнфорда: академические направления, кампус, исследования и публикации.',
    image: '/portfolio/stanford.jpg',
    tags: ['University', 'Research', 'UX'],
    link: 'https://www.stanford.edu',
    color: 'from-indigo-600 to-blue-700',
    year: '2024',
    icon: '📚',
    location: 'США',
  },

  // Энергетика
  {
    id: 93,
    title: 'ExxonMobil',
    category: 'Энергетика',
    type: 'web',
    description: 'Корпоративный ресурс энергетической компании: бизнес-направления, проекты и инвесторская информация.',
    image: '/portfolio/exxonmobil.jpg',
    tags: ['Energy', 'Corporate', 'Enterprise'],
    link: 'https://corporate.exxonmobil.com',
    color: 'from-emerald-600 to-green-700',
    year: '2024',
    icon: '⚡',
    location: 'США',
  },
  {
    id: 94,
    title: 'Suncor Energy',
    category: 'Энергетика',
    type: 'web',
    description: 'Портал энергетической компании: продукты, устойчивое развитие и корпоративный контент.',
    image: '/portfolio/suncor.jpg',
    tags: ['Energy', 'Utilities', 'Digital'],
    link: 'https://www.suncor.com',
    color: 'from-emerald-600 to-green-700',
    year: '2025',
    icon: '⚡',
    location: 'Канада',
  },

  // Развлечения
  {
    id: 95,
    title: 'Disney+',
    category: 'Развлечения',
    type: 'web',
    description: 'Стриминговая платформа: каталог, подписки, рекомендации и мультиязычные сервисы.',
    image: '/portfolio/disney-plus.jpg',
    tags: ['Streaming', 'Video', 'Platform'],
    link: 'https://www.disneyplus.com',
    color: 'from-rose-600 to-red-700',
    year: '2024',
    icon: '🎮',
    location: 'США',
  },

  // Консалтинг
  {
    id: 96,
    title: 'Bain & Company',
    category: 'Консалтинг',
    type: 'web',
    description: 'Корпоративный сайт консалтинговой компании: практики, исследования и кейсы для клиентов.',
    image: '/portfolio/bain.jpg',
    tags: ['Consulting', 'Strategy', 'Insights'],
    link: 'https://www.bain.com',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'США',
  },
  {
    id: 97,
    title: 'Strategy&',
    category: 'Консалтинг',
    type: 'web',
    description: 'Сайт подразделения стратегического консалтинга: аналитика, решения и отраслевой контент.',
    image: '/portfolio/strategyand.jpg',
    tags: ['Consulting', 'Strategy', 'B2B'],
    link: 'https://www.strategyand.pwc.com',
    color: 'from-sky-700 to-blue-900',
    year: '2025',
    icon: '📊',
    location: 'США',
  },
  {
    id: 98,
    title: 'KPMG Netherlands',
    category: 'Консалтинг',
    type: 'web',
    description: 'Сайт консалтинговой и аудиторской компании для рынка Нидерландов: услуги, новости и публикации.',
    image: '/portfolio/kpmg-nl.jpg',
    tags: ['Consulting', 'Audit', 'Enterprise'],
    link: 'https://kpmg.com/nl/en/home.html',
    color: 'from-sky-700 to-blue-900',
    year: '2024',
    icon: '📊',
    location: 'Нидерланды',
  }
]

export function getFeaturedRank(project: PortfolioProject): number {
  const normalized = normalizePortfolioLink(project.link)
  const idx = PORTFOLIO_PRIORITY_LINKS.findIndex(
    (link) => normalizePortfolioLink(link) === normalized
  )
  return idx === -1 ? Number.MAX_SAFE_INTEGER : idx
}

export function getFeaturedPortfolioProjects(): PortfolioProject[] {
  return PORTFOLIO_PRIORITY_LINKS.map((link) =>
    PORTFOLIO_PROJECTS.find(
      (p) => normalizePortfolioLink(p.link) === normalizePortfolioLink(link)
    )
  ).filter((p): p is PortfolioProject => p != null)
}

/** Получить slug из внутренней ссылки /portfolio/xxx */
export function getSlugFromLink(link: string): string | null {
  if (link.startsWith('/portfolio/')) {
    return link.replace(/^\/portfolio\/?/, '').trim() || null
  }
  return null
}

export function getProjectBySlug(slug: string): PortfolioProject | undefined {
  return PORTFOLIO_PROJECTS.find((p) => getSlugFromLink(p.link) === slug)
}
