/** Внутренние страницы /portfolio/[slug] для sitemap.xml */
export const PORTFOLIO_SITEMAP_SLUGS = [
  'amba-detail',
  'nexton',
  'maxximum',
  'dynamo-vitebsk',
  'bmservice',
  'artdetailing',
  'sparkite',
  'buzz',
  'erin',
  'vsenashi',
  'vigbo',
  'nordforge-industrial',
  'meridian-ledger',
  'harbor-health',
  'oak-and-thread',
  'clearroute-logistics',
  'brightpath-academy',
  'solara-grid',
  'stagewire-events',
  'apex-advisory',
] as const
